config/routes.rb
Rails.application.routes.draw do
  resources :grams, :users
  root 'grams#index'

  resources :grams, except: [:edit, :update]
  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/gram.rb
class Gram < ActiveRecord::Base
  validates_presence_of :title, :description, :location_code
  validates_length_of :description, minimum: 10

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
   validates_presence_of :name, :email
   validates_uniqueness_of :email, case_sensitive: false
   validates_format_of :email, with: /@/

   before_save { self.email = email.downcase }

   has_secure_password

   has_many :grams
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

end

app/controllers/concerns/grams_controller.rb
class GramsController < ApplicationController
  def index
    @grams = Gram.page(params[:page]).per(5)
  end

  def new

    redirect_to root_path unless current_user
    @gram = Gram.new
  end

  def create
    @gram = Gram.new(model_params)
    @gram.user = current_user
    if @gram.save
      flash[:notice] = 'Gram successfully created'
      redirect_to @gram
    else
      render :new
  end
end
  def show
    @gram = Gram.find(params[:id])
  end

  def destroy
    @gram = Gram.find(params[:id])
    @gram.destroy
    redirect_to grams_path
  end

  private

  def model_params
   params.require(:gram).permit(:title, :description, :location_code, :image_url)
  end

end

app/controllers/concerns/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user.present? && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash.now[:error] = 'Invalid email/password'
      render :new
    end
  end
    def destroy
      session.delete(:user_id)
      @current_user = nil

      redirect_to root_path
    end
end

app/controllers/concerns/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(model_params)
    if @user.save
      flash[:notice] = 'User successfully created!'
      redirect_to @user
    else
      flash.now[:error] = 'Failed to create user!'
      render :new
  end
end
  def show
    @user = User.find(params[:id])
    @grams = @user.grams.page(params[:page]).per(5)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def model_params
   params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
def country_name(country_code)
  country = ISO3166::Country[country_code]
  country.translations[I18n.locale.to_s]
end


end

app/views/grams/index.html.erb
<% if current_user %>

<div class='new-gram text-center'>
    <%= link_to icon('camera'), new_gram_path %>
</div>
<% end %>

<% @grams.each do |gram| %>
  <div class='row'>
    <div class='col-sm-6 col-sm-offset-3'>
      <div class='panel panel-default'>
        <div class='panel-heading'>
          <div class='row'>
            <div class='col-sm-6'>
              Me
            </div>
            <div class='col-sm-6 text-right'>
              <span class='created_at'><%= link_to time_ago_in_words(gram.created_at), gram_path(gram) %></span>
              &nbsp;
              <% if current_user %>
              <%= link_to icon('trash-o'), gram_path(@gram), method: :delete, data: { confirm: 'Are you sure you want to delete this Gram?'} %>
              <% end %>
            </div>
          </div>
        </div>
        <div class='panel-body'>
          <div><%= image_tag gram.image_url %></div>
        </div>
        <div class='panel-footer'>
          <div class='gram-title'><%= gram.title %></div>
          <div class='gram-location'><%= icon('map-marker') %> <%= country_name(gram.location_code) %></div>
          <div class='gram-content'><%= gram.description %></div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class='text-center'>
  <%= paginate @grams %>
</div>

app/views/grams/new.html.erb
<div class='row'>
  <div class='col-sm-6 col-sm-offset-3'>
    <%= form_for @gram do |f| %>
      <% if @gram.errors.any? %>
        <div class='alert alert-danger'>
          <ul>
            <% @gram.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class='form-group text-center'>
        <%= f.hidden_field :image_url, role: 'uploadcare-uploader', data: {crop: '600:600', 'images-only' => true} %>
      </div>

      <hr/>

      <div class='form-group'>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= f.label :country_code %>
        <%= f.country_select :location_code, { include_blank: true, priority_countries: ['SG', 'MY'] }, { class: 'form-control' } %>
      </div>

      <hr/>

      <div>
        <%= f.submit class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/grams/show.html.erb
<div class='row'>
  <div class='col-sm-6 col-sm-offset-3'>
    <div class='panel panel-default'>
      <div class='panel-heading'>
        <div class='row'>
          <div class='col-sm-6'>
            Me
          </div>
          <div class='col-sm-6 text-right'>
            <span class='created_at'><%= link_to time_ago_in_words(@gram.created_at), gram_path(@gram) %></span>
            &nbsp;

            <% if current_user %>
            <%= link_to icon('trash-o'), gram_path(@gram), method: :delete, data: { confirm: 'Are you sure you want to delete this Gram?'} %>
          <% end %>
          </div>
        </div>
      </div>
      <div class='panel-body'>
        <div><%= image_tag @gram.image_url %></div>
      </div>
      <div class='panel-footer'>
        <div class='gram-title'><%= @gram.title %></div>
        <div class='gram-location'><%= icon('map-marker') %> <%= country_name(@gram.country_code) %></div>
        <div class='gram-content'><%= @gram.content %></div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Minigram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script>
  UPLOADCARE_PUBLIC_KEY = "a3a9b6a525e63a805008";
</script>
<script charset="utf-8" src="//ucarecdn.com/widget/2.8.2/uploadcare/uploadcare.full.min.js"></script>

<nav class="navbar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">minigram</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse pull-right">
      <ul class="nav navbar-nav">
        <!--<li><a href="#">About</a></li>-->

        <% if current_user %>
          <li><%= link_to 'My Minigram', user_path(current_user) %></li>
          <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
        <% else%>
          <li><%= link_to 'Sign Up', new_user_path %></li>
          <li><%= link_to 'Login', login_path %></li>
        <% end%>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <% if flash[:notice] %>
    <div class="alert alert-info"><%= flash[:notice] %></div>
  <% end %>

  <% if flash[:error] %>
    <div class="alert alert-info"><%= flash[:notice] %></div>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/users/index.html.erb
<% @users.each do |user| %>
<div>
  <div>
  <%= link_to(user.name, user) %>
  </div>

  <div>
  <%= user.email %>
  </div>

  <div>
    <%= link_to('Delete', user, method: :delete) %>
  </div>

</div>
<hr>
<% end %>

app/views/users/new.html.erb
<div class='row'>
  <div class='col-sm-6 col-sm-offset-3'>
    <% if @user.errors.any? %>
      <div class='alert alert-danger'>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_for(@user) do |f| %>
      <div class='form-group'>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class='form-group'>
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>

      <div class='form-group'>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class='form-group'>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <div>
        <%= f.submit 'Sign Up', class: 'btn btn-success' %>
      </div>
  <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class='new-gram text-center'>
    <%= link_to icon('camera'), new_gram_path %>
</div>

<% @grams.each do |gram| %>
  <div class='row'>
    <div class='col-sm-6 col-sm-offset-3'>
      <div class='panel panel-default'>
        <div class='panel-heading'>
          <div class='row'>
            <div class='col-sm-6'>
              Me
            </div>
            <div class='col-sm-6 text-right'>
              <span class='created_at'><%= link_to time_ago_in_words(gram.created_at), gram_path(gram) %></span>
              &nbsp;
              <% if current_user %>
              <%= link_to icon('trash-o'), gram_path(@gram), method: :delete, data: { confirm: 'Are you sure you want to delete this Gram?'} %>
              <% end %>
            </div>
          </div>
        </div>
        <div class='panel-body'>
          <div><%= image_tag gram.image_url %></div>
        </div>
        <div class='panel-footer'>
          <div class='gram-title'><%= gram.title %></div>
          <div class='gram-location'><%= icon('map-marker') %> <%= country_name(gram.location_code) %></div>
          <div class='gram-content'><%= gram.description %></div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class='text-center'>
  <%= paginate @grams %>
</div>